### PR TITLE
CSV import improvements

### LINKED ISSUE #1389: CSV Import - Imports to class, not subclass
**Describe the bug**

On the newest version of Realm Studio, when I click "Import from CSV", the items appear in the superclass instead of the subclass. 

**To Reproduce**
1. Create a class and then subclass in a realm database. 
(For me, the superclass is "Card" and I have various types of cards.)

2. From Realm Studio, go to Import Data From... CSV. Select a CSV file with a name that matches the subclass. The data will be imported into the superclass and not the subclass. 
(In prior versions, I'd select the CSV with the file name that corresponds to my subclass and select import. All data would then be imported into the subclass. Now, regardless of the name of the CSV, the data goes to the superclass and data from the properties specific to my subclasses is lost. 

**Expected behavior**
I expected the data to be imported into the subclass, as was the case in prior versions. 

**Screenshots**

See attached. 
-"Old Version" shows the correct import into Notes (subclass). 
-"New Version" shows the incorrect import into Card (superclass). 

**Versions:**
 - OS: 11.0.1
 - Studio Version:  10.1.1
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**
On new version
On old version

### PR DESCRIPTION
**Pull request by kraenhansen**
This fixes #1389 by adding a prompt for users to choose the destination class name for each file imported into an existing Realm.

Screenshot 2021-02-08 at 15 01 14

### CODE REVIEW

File: src/services/data-importer/csv/CSVDataImporter.ts [hunk 1]
```diff
@@ -18,60 +18,54 @@
 
 import fs from 'fs-extra';
 import papaparse from 'papaparse';
+import { ObjectSchemaProperty, PropertyType } from 'realm';
 
-import { DataImporter } from '../DataImporter';
+import { DataImporter, ImportableFile } from '../DataImporter';
 
 export class CSVDataImporter extends DataImporter {
   private static readonly NUMBER_OF_INSERTS_BEFORE_COMMIT = 10000;
```
Comment (steffenagger) [inline src/services/data-importer/csv/CSVDataImporter.ts:26]: (I know this isn't a part of the changes, but...) Does batch commits make sense in transactions? I would argue it contradicts transactions.

File: src/services/data-importer/csv/CSVDataImporter.ts [hunk 2]
```diff
@@ -18,60 +18,54 @@
...
-                    throw new Error(
-                      `Can not parse ${row[prop]} as int at line ${lineIndex}`,
-                    );
-                  }
-                  object[prop] = floatNumber;
-                  break;
-                default:
-                  // string?
-                  object[prop] = row[prop];
+              if (propertySchema.optional && dataValue === '') {
```
Comment (steffenagger) [inline src/services/data-importer/csv/CSVDataImporter.ts:56]: Comment: This seems wrong, or at least hard to actually insert empty strings on optional fields, but it seems this is a limitation in the CSV standard.

**Review by steffenagger — COMMENTED** [review]
Looks good, except `showMessageBoxSync` doesn't really fit the task. Do we have any other usable (custom) popups implemented, we could use?

File: src/services/data-importer/csv/CSVDataImporter.ts (hunk 2 above)
Comment (kraenhansen) [reply src/services/data-importer/csv/CSVDataImporter.ts:56]: Yeah, I agree. There is the edge case of empty strings. Ideally this should be a setting when importing.
Since its possible to go from `null` to an empty string via the UI (although thats 1 operation per row) but not the other way around, I think this is a good default for now (until we decide to invest more in this).

File: src/services/data-importer/csv/CSVDataImporter.ts (hunk 1 above)
Comment (kraenhansen) [reply src/services/data-importer/csv/CSVDataImporter.ts:26]: It makes sense? The implementation opens a write transaction, inserts up to 10000 objects and then commits and opens a new transaction. It's like wrapping every 10000 `create` calls in a `write` call.

Comment (steffenagger) [reply src/services/data-importer/csv/CSVDataImporter.ts:26]: Yes, but if you are importing a 20.000 rows csv, would you be interested in just the first 10.000 in the db, if something fails for the remaining 10.000? (Isn't that what potentially could happen?)

Comment (kraenhansen) [reply src/services/data-importer/csv/CSVDataImporter.ts:26]: You're right 👍  I think there's a trade-off here, but I can't remember why we shouldn't just make one huge transaction.

**Review by steffenagger — APPROVED** [review]
Looks good.
A couple of console.logs left in, and perhaps disable the `import` button, when target classes hasn't been selected?

**Review by steffenagger — APPROVED** [review]
